### ISSUE TITLE
New modpack version (1.0.4.) does not start

### ISSUE THREAD

**Issue by Zkera** [ShadowKing21228/Journey-to-Dawn#1]
This is what I got after launching the new version:

[18:41:35] [INIT] KubeJS 1902.6.2-build.73; MC 1902 forge
[18:41:35] [INIT] Loaded plugins:
[18:41:35] [INIT] - dev.latvian.mods.kubejs.forge.BuiltinKubeJSForgePlugin
[18:41:35] [INIT] - dev.latvian.mods.kubejs.forge.BuiltinKubeJSForgeClientPlugin
[18:41:35] [INIT] - dev.ftb.mods.ftbxmodcompat.ftbquests.kubejs.KubeJSIntegration
[18:41:35] [INIT] - dev.ftb.mods.ftbxmodcompat.ftbteams.kubejs.FTBTeamsKubeJSPlugin
[18:41:35] [INIT] - qinomed.kubejsdelight.KubeJSDelightPlugin
[18:41:35] [INIT] - com.almostreliable.ponderjs.PonderJSPlugin
[18:41:36] [INFO] Loaded script startup_scripts:blocks.js in 0.129 s
[18:41:36] [INFO] Loaded script startup_scripts:create.js in 0.002 s
[18:41:36] [INFO] example.js#5: Hello, World! (Loaded startup scripts)
[18:41:36] [INFO] Loaded script startup_scripts:example.js in 0.001 s
[18:41:36] [INFO] Loaded script startup_scripts:idols.js in 0.009 s
[18:41:36] [INFO] Loaded script startup_scripts:items.js in 0.005 s
[18:41:36] [INFO] Loaded script startup_scripts:lategame.js in 0.006 s
[18:41:36] [INFO] Loaded script startup_scripts:music.js in 0.004 s
[18:41:36] [INFO] Loaded script startup_scripts:scripts.js in 0.006 s
[18:41:36] [INFO] Loaded script startup_scripts:tablets/1.js in 0.0 s
[18:41:36] [INFO] Loaded script startup_scripts:tablets/10.js in 0.0 s
[18:41:36] [INFO] Loaded script startup_scripts:tablets/2.js in 0.0 s
[18:41:36] [INFO] Loaded script startup_scripts:tablets/3.js in 0.001 s
[18:41:36] [INFO] Loaded script startup_scripts:tablets/4.js in 0.001 s
[18:41:36] [INFO] Loaded script startup_scripts:tablets/5.js in 0.0 s
[18:41:36] [INFO] Loaded script startup_scripts:tablets/6.js in 0.0 s
[18:41:36] [INFO] Loaded script startup_scripts:tablets/7.js in 0.001 s
[18:41:36] [INFO] Loaded script startup_scripts:tablets/8.js in 0.0 s
[18:41:36] [INFO] Loaded script startup_scripts:tablets/9.js in 0.001 s
[18:41:36] [INFO] Loaded script startup_scripts:tablets.js in 0.003 s
[18:41:36] [INFO] Loaded 19/19 KubeJS startup scripts in 1.313 s
[18:41:37] [ERROR] ! Error occurred while handling event 'StartupEvents.registry': java.lang.IllegalArgumentException: Duplicate key 'kubejs:lost_tablet_a' in registry 'minecraft:item'!
[18:41:37] [ERROR] ! java.lang.IllegalArgumentException: Duplicate key 'kubejs:lost_tablet_a' in registry 'minecraft:item'!
[18:41:37] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.73/dev.latvian.mods.kubejs.registry.RegistryInfo.addBuilder(RegistryInfo.java:259)
[18:41:37] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.73/dev.latvian.mods.kubejs.registry.RegistryEventJS.create(RegistryEventJS.java:52)
[18:41:37] [ERROR] ! 	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
[18:41:37] [ERROR] ! 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:41:37] [ERROR] ! 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.MemberBox.invoke(MemberBox.java:160)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:987)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:370)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Context.doTopCall(Context.java:1325)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.ArrowFunction.call(ArrowFunction.java:42)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[18:41:37] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[18:41:37] [ERROR] ! 	at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy105.onEvent(Unknown Source)
[18:41:37] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.73/dev.latvian.mods.kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[18:41:37] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.73/dev.latvian.mods.kubejs.event.EventHandler.postToHandlers(EventHandler.java:301)
[18:41:37] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.73/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:263)
[18:41:37] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.73/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:225)
[18:41:37] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.73/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:204)
[18:41:37] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.73/dev.latvian.mods.kubejs.KubeJS.<init>(KubeJS.java:164)
[18:41:37] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.73/dev.latvian.mods.kubejs.forge.KubeJSForge.<init>(KubeJSForge.java:37)
[18:41:37] [ERROR] ! 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:41:37] [ERROR] ! 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[18:41:37] [ERROR] ! 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:41:37] [ERROR] ! 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:41:37] [ERROR] ! 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:41:37] [ERROR] ! 	at LAYER PLUGIN/javafmllanguage@1.19.2-43.4.0/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70)
[18:41:37] [ERROR] ! 	at LAYER PLUGIN/fmlcore@1.19.2-43.4.0/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122)
[18:41:37] [ERROR] ! 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[18:41:37] [ERROR] ! 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[18:41:37] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[18:41:37] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[18:41:37] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[18:41:37] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[18:41:37] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

[startup.log](https://github.com/user-attachments/files/17269981/startup.log)
![image](https://github.com/user-attachments/assets/64a53a31-83fd-407a-a23e-6a1bc40449fb)

**Comment by Zkera** [comment]
sorry, it seems that this problem is not related to the modpack, since when returning to the previous version, the same thing happens
![image](https://github.com/user-attachments/assets/35d3ef0a-7296-4942-bc92-a5901d75a894)
